### PR TITLE
Sp4 270 edit phone number from profile and testing it fe

### PR DESCRIPTION
**Pull request by serhiibets**
Important to check: 
 - need to check reCapcha on physical android phones
 - need to check on different phone number (who has two numbers) how new phone number save into current user.

### CODE REVIEW

**Comment by econesag** [comment]
The resend code Text is still overflowing in some devices.

**Review by econesag — CHANGES_REQUESTED** [review]
- [x] The text of Resend code it's still overflowing in some devices
- [x] If the edit page is in landscape appears and overflow (try to add a SingleChildScrollView)
- [ ] Once the phone has change is not updated on the UI.
- [ ] When you put an incorrect code the error is not managed.
- [x] Resend Code.
- [ ] Timeout.
- [x] The dialog of Invalid Mobile Number must be in corrected in Spanish version
- [x] the ? is missing in didnotReceiveCode at the spanish version

**Comment by econesag** [comment]
Remember to work with the correct file structure

**Comment by econesag** [comment]
It's not possible to set a timeout for the code, in fact, if anyone tries to resend the code it will send the same code number.

**Review by econesag — APPROVED** [review]

**Review by capf4bbo — APPROVED** [review]

**Pull request merged**
